param([switch]$SkipPython)
$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$configDir=Join-Path $root 'Config'
New-Item -ItemType Directory -Force -Path $configDir | Out-Null
if(-not (Test-Path (Join-Path $configDir 'config.yaml'))){ Copy-Item (Join-Path $configDir 'config.example.yaml') (Join-Path $configDir 'config.yaml') }
if(-not (Test-Path (Join-Path $configDir 'secrets.local'))){ Copy-Item (Join-Path $configDir 'secrets.local.example') (Join-Path $configDir 'secrets.local') }

function Get-ProjectPython {
  $embedded=Join-Path $root 'Runtime\python\python.exe'
  if(Test-Path $embedded){ return $embedded }
  $venv=Join-Path $root 'Runtime\python\Scripts\python.exe'
  if(Test-Path $venv){ return $venv }
  return $null
}

Write-Host '=== GoldTradingSystem installer ===' -ForegroundColor Cyan
Write-Host "Project root: $root"

$mt5=@()
$termRoot=Join-Path $env:APPDATA 'MetaQuotes\Terminal'
if(Test-Path $termRoot){
  foreach($d in Get-ChildItem $termRoot -Directory){
    $originFile=Join-Path $d.FullName 'origin.txt'
    if(Test-Path $originFile){
      $origin=(Get-Content $originFile -Raw).Trim()
      $meta=''
      $originDir=$origin
      if(Test-Path $origin -PathType Leaf){ $originDir=Split-Path $origin }
      foreach($candidate in @((Join-Path $originDir 'metaeditor64.exe'),(Join-Path $originDir 'metaeditor.exe'))){
        if(Test-Path $candidate){$meta=$candidate;break}
      }
      $mt5 += [PSCustomObject]@{DataPath=$d.FullName;Origin=$origin;MetaEditor=$meta}
    }
  }
}
if($mt5.Count -eq 0){ throw 'No MT5 data directory was detected. Start the target MT5 terminal once and rerun this installer.' }
Write-Host "`nDetected MT5 instances:"
for($i=0;$i -lt $mt5.Count;$i++){ Write-Host "[$($i+1)] $($mt5[$i].Origin)  ->  $($mt5[$i].DataPath)" }
$choice=1
if($mt5.Count -gt 1){
  $raw=Read-Host 'Enter the MT5 number to use'
  if(-not [int]::TryParse($raw,[ref]$choice) -or $choice -lt 1 -or $choice -gt $mt5.Count){ throw 'Invalid MT5 selection.' }
}
$selected=$mt5[$choice-1]

$atasRaw=@()
if($env:LOCALAPPDATA){
  $atasRaw += (Join-Path $env:LOCALAPPDATA 'ATAS')
  $atasRaw += (Join-Path $env:LOCALAPPDATA 'ATAS Platform')
  $atasRaw += (Join-Path $env:LOCALAPPDATA 'Programs\ATAS')
}
if($env:APPDATA){
  $atasRaw += (Join-Path $env:APPDATA 'ATAS')
  $atasRaw += (Join-Path $env:APPDATA 'ATAS Platform')
}
if($env:ProgramFiles){
  $atasRaw += (Join-Path $env:ProgramFiles 'ATAS')
  $atasRaw += (Join-Path $env:ProgramFiles 'ATAS Platform')
}
$pf86=[Environment]::GetEnvironmentVariable('ProgramFiles(x86)')
if($pf86){
  $atasRaw += (Join-Path $pf86 'ATAS')
  $atasRaw += (Join-Path $pf86 'ATAS Platform')
}
$atasCandidates=@($atasRaw | Where-Object {$_ -and (Test-Path $_)} | Select-Object -Unique)
$atasPath=''
if($atasCandidates.Count -gt 0){
  Write-Host "`nDetected ATAS paths:"
  for($i=0;$i -lt $atasCandidates.Count;$i++){Write-Host "[$($i+1)] $($atasCandidates[$i])"}
  $a=1
  if($atasCandidates.Count -gt 1){
    $raw=Read-Host 'Enter the ATAS number to use'
    if(-not [int]::TryParse($raw,[ref]$a) -or $a -lt 1 -or $a -gt $atasCandidates.Count){throw 'Invalid ATAS selection.'}
  }
  $atasPath=$atasCandidates[$a-1]
} else {
  Write-Warning 'ATAS was not detected automatically. You can set Config/paths.yaml later. Guardian local protection is not blocked by this.'
}
$atasTarget=''
if($env:APPDATA){ $atasTarget=Join-Path $env:APPDATA 'ATAS\Indicators' }

function YamlQuote([string]$v){
  if($null -eq $v){$v=''}
  return '"' + $v.Replace('\','/').Replace('"','\"') + '"'
}
$paths=@"
# Generated by Tools/install.ps1. Machine-specific paths only.
mt5:
  terminal_data_path: $(YamlQuote $selected.DataPath)
  terminal_origin: $(YamlQuote $selected.Origin)
  metaeditor_path: $(YamlQuote $selected.MetaEditor)
atas:
  install_path: $(YamlQuote $atasPath)
  bridge_target_path: $(YamlQuote $atasTarget)
"@
Set-Content -Path (Join-Path $configDir 'paths.yaml') -Value $paths -Encoding UTF8
Write-Host '[Config] Wrote Config/paths.yaml'

& (Join-Path $PSScriptRoot 'deploy_mt5.ps1') -TerminalDataPath $selected.DataPath -MetaEditorPath $selected.MetaEditor

$atasBound=$false
if(-not [string]::IsNullOrWhiteSpace($atasPath)){
  try {
    & (Join-Path $PSScriptRoot 'deploy_atas.ps1') -AtasInstallPath $atasPath -TargetPath $atasTarget
    $atasBound=($LASTEXITCODE -eq 0)
  } catch {
    Write-Warning ("ATAS SDK binding is not complete: " + $_.Exception.Message)
    Write-Warning 'Installer will continue. ATAS SDK Bridge must compile and load successfully before final acceptance.'
  }
}

$py=Get-ProjectPython
if($py){
  Write-Host "[Runtime] Project Python detected: $py"
} elseif(-not $SkipPython){
  & (Join-Path $PSScriptRoot 'install_runtime.ps1')
  $py=Get-ProjectPython
}

if($py){
  & $py (Join-Path $PSScriptRoot 'validate_config.py')
  if($LASTEXITCODE -ne 0){ throw 'Configuration validation failed.' }
  & $py (Join-Path $PSScriptRoot 'run_smoke_test.py')
  if($LASTEXITCODE -ne 0){ throw 'Smoke test failed.' }
} elseif($SkipPython){
  Write-Warning 'SkipPython was specified and no project Python runtime was found. Prepare Python before starting the system.'
} else {
  throw 'Python runtime preparation failed.'
}

Write-Host "`n=== Automated installation steps completed ===" -ForegroundColor Green
if($atasBound){
  Write-Host '[ATAS] SDK Bridge compiled against the local ATAS assemblies and was deployed.' -ForegroundColor Green
} else {
  Write-Warning '[ATAS] SDK Bridge still requires local compile/load verification.'
}
Write-Host 'Machine acceptance still requires Rithmic Paper, MT5 localhost socket permission, ATAS chart Bridge loading, Demo trading, disconnect, and weekend tests.'
