param([switch]$SkipPython)
$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$configDir=Join-Path $root 'Config'
New-Item -ItemType Directory -Force -Path $configDir | Out-Null
if(-not (Test-Path (Join-Path $configDir 'config.yaml'))){ Copy-Item (Join-Path $configDir 'config.example.yaml') (Join-Path $configDir 'config.yaml') }
if(-not (Test-Path (Join-Path $configDir 'secrets.local'))){ Copy-Item (Join-Path $configDir 'secrets.local.example') (Join-Path $configDir 'secrets.local') }

function Get-ProjectPython {
  $embedded=Join-Path $root 'Runtime\python\python.exe'
  if(Test-Path $embedded){ return $embedded }
  $venv=Join-Path $root 'Runtime\python\Scripts\python.exe'
  if(Test-Path $venv){ return $venv }
  return $null
}

Write-Host '=== GoldTradingSystem 新电脑安装器 ===' -ForegroundColor Cyan
Write-Host "主目录: $root"

$mt5=@()
$termRoot=Join-Path $env:APPDATA 'MetaQuotes\Terminal'
if(Test-Path $termRoot){
  foreach($d in Get-ChildItem $termRoot -Directory){
    $originFile=Join-Path $d.FullName 'origin.txt'
    if(Test-Path $originFile){
      $origin=(Get-Content $originFile -Raw).Trim()
      $meta=''
      $originDir=$origin
      if(Test-Path $origin -PathType Leaf){ $originDir=Split-Path $origin }
      foreach($candidate in @((Join-Path $originDir 'metaeditor64.exe'),(Join-Path $originDir 'metaeditor.exe'))){
        if(Test-Path $candidate){$meta=$candidate;break}
      }
      $mt5 += [PSCustomObject]@{DataPath=$d.FullName;Origin=$origin;MetaEditor=$meta}
    }
  }
}
if($mt5.Count -eq 0){ throw '未检测到 MT5 数据目录。请至少启动一次目标 MT5 后重新运行安装器。' }
Write-Host "`n检测到 MT5 实例："
for($i=0;$i -lt $mt5.Count;$i++){ Write-Host "[$($i+1)] $($mt5[$i].Origin)  ->  $($mt5[$i].DataPath)" }
$choice=1
if($mt5.Count -gt 1){
  $raw=Read-Host '请输入要使用的 MT5 编号'
  if(-not [int]::TryParse($raw,[ref]$choice) -or $choice -lt 1 -or $choice -gt $mt5.Count){ throw 'MT5 选择无效。' }
}
$selected=$mt5[$choice-1]

$atasRaw=@()
if($env:LOCALAPPDATA){
  $atasRaw += (Join-Path $env:LOCALAPPDATA 'ATAS')
  $atasRaw += (Join-Path $env:LOCALAPPDATA 'ATAS Platform')
  $atasRaw += (Join-Path $env:LOCALAPPDATA 'Programs\ATAS')
}
if($env:APPDATA){
  $atasRaw += (Join-Path $env:APPDATA 'ATAS')
  $atasRaw += (Join-Path $env:APPDATA 'ATAS Platform')
}
if($env:ProgramFiles){
  $atasRaw += (Join-Path $env:ProgramFiles 'ATAS')
  $atasRaw += (Join-Path $env:ProgramFiles 'ATAS Platform')
}
$pf86=[Environment]::GetEnvironmentVariable('ProgramFiles(x86)')
if($pf86){
  $atasRaw += (Join-Path $pf86 'ATAS')
  $atasRaw += (Join-Path $pf86 'ATAS Platform')
}
$atasCandidates=@($atasRaw | Where-Object {$_ -and (Test-Path $_)} | Select-Object -Unique)
$atasPath=''
if($atasCandidates.Count -gt 0){
  Write-Host "`n检测到 ATAS 路径："
  for($i=0;$i -lt $atasCandidates.Count;$i++){Write-Host "[$($i+1)] $($atasCandidates[$i])"}
  $a=1
  if($atasCandidates.Count -gt 1){
    $raw=Read-Host '请输入 ATAS 编号'
    if(-not [int]::TryParse($raw,[ref]$a) -or $a -lt 1 -or $a -gt $atasCandidates.Count){throw 'ATAS 选择无效。'}
  }
  $atasPath=$atasCandidates[$a-1]
} else {
  Write-Warning '未自动检测到 ATAS。稍后可手工填写 Config/paths.yaml；这不会阻止 Guardian 本地保护。'
}
$atasTarget=if($env:APPDATA){ Join-Path $env:APPDATA 'ATAS\Indicators' } else { '' }

function YamlQuote([string]$v){
  if($null -eq $v){$v=''}
  return '"' + $v.Replace('\','/').Replace('"','\"') + '"'
}
$paths=@"
# Generated by Tools/install.ps1. Machine-specific paths only.
mt5:
  terminal_data_path: $(YamlQuote $selected.DataPath)
  terminal_origin: $(YamlQuote $selected.Origin)
  metaeditor_path: $(YamlQuote $selected.MetaEditor)
atas:
  install_path: $(YamlQuote $atasPath)
  bridge_target_path: $(YamlQuote $atasTarget)
"@
Set-Content -Path (Join-Path $configDir 'paths.yaml') -Value $paths -Encoding UTF8
Write-Host '[Config] 已写入 Config/paths.yaml'

& (Join-Path $PSScriptRoot 'deploy_mt5.ps1') -TerminalDataPath $selected.DataPath -MetaEditorPath $selected.MetaEditor

$atasBound=$false
if(-not [string]::IsNullOrWhiteSpace($atasPath)){
  try {
    & (Join-Path $PSScriptRoot 'deploy_atas.ps1') -AtasInstallPath $atasPath -TargetPath $atasTarget
    $atasBound=($LASTEXITCODE -eq 0)
  } catch {
    Write-Warning ("ATAS SDK 自动绑定暂未完成: " + $_.Exception.Message)
    Write-Warning '安装器继续；Guardian/Python 可先准备。最终验收前必须让 ATAS SDK Bridge 本机编译并加载成功。'
  }
}

$py=Get-ProjectPython
if($py){
  Write-Host "[Runtime] 检测到项目内 Python: $py"
} elseif(-not $SkipPython){
  & (Join-Path $PSScriptRoot 'install_runtime.ps1')
  $py=Get-ProjectPython
}

if($py){
  & $py (Join-Path $PSScriptRoot 'validate_config.py')
  if($LASTEXITCODE -ne 0){ throw '配置校验失败。' }
  & $py (Join-Path $PSScriptRoot 'run_smoke_test.py')
  if($LASTEXITCODE -ne 0){ throw 'Smoke test 失败。' }
} elseif($SkipPython){
  Write-Warning '已指定 -SkipPython，且项目中未找到 Python runtime；启动系统前必须自行准备。'
} else {
  throw 'Python runtime 准备失败。'
}

Write-Host "`n=== 仓库侧自动安装步骤完成 ===" -ForegroundColor Green
if($atasBound){
  Write-Host '[ATAS] SDK Bridge 已针对本机 ATAS 程序集编译并部署。' -ForegroundColor Green
} else {
  Write-Warning '[ATAS] SDK Bridge 仍需在本机完成编译/加载验证。'
}
Write-Host '最终仍需实机完成：Rithmic Paper 连接、MT5 允许 127.0.0.1 Socket、ATAS 图表加载 Bridge、模拟盘开平仓/断线/周末验收。'
