param([switch]$SkipPython)
$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$configDir=Join-Path $root 'Config'
New-Item -ItemType Directory -Force -Path $configDir | Out-Null
if(-not (Test-Path (Join-Path $configDir 'config.yaml'))){ Copy-Item (Join-Path $configDir 'config.example.yaml') (Join-Path $configDir 'config.yaml') }
if(-not (Test-Path (Join-Path $configDir 'secrets.local'))){ Copy-Item (Join-Path $configDir 'secrets.local.example') (Join-Path $configDir 'secrets.local') }

Write-Host '=== GoldTradingSystem 新电脑安装器 ===' -ForegroundColor Cyan
Write-Host "主目录: $root"

$mt5=@()
$termRoot=Join-Path $env:APPDATA 'MetaQuotes\Terminal'
if(Test-Path $termRoot){
  foreach($d in Get-ChildItem $termRoot -Directory){
    $originFile=Join-Path $d.FullName 'origin.txt'
    if(Test-Path $originFile){
      $origin=(Get-Content $originFile -Raw).Trim()
      $meta=''
      $originDir=$origin
      if(Test-Path $origin -PathType Leaf){ $originDir=Split-Path $origin }
      foreach($candidate in @((Join-Path $originDir 'metaeditor64.exe'),(Join-Path $originDir 'metaeditor.exe'))){
        if(Test-Path $candidate){$meta=$candidate;break}
      }
      $mt5 += [PSCustomObject]@{DataPath=$d.FullName;Origin=$origin;MetaEditor=$meta}
    }
  }
}
if($mt5.Count -eq 0){ throw '未检测到 MT5 数据目录。请至少启动一次目标 MT5 后重新运行安装器。' }
Write-Host "`n检测到 MT5 实例："
for($i=0;$i -lt $mt5.Count;$i++){ Write-Host "[$($i+1)] $($mt5[$i].Origin)  ->  $($mt5[$i].DataPath)" }
$choice=1
if($mt5.Count -gt 1){
  $raw=Read-Host '请输入要使用的 MT5 编号'
  if(-not [int]::TryParse($raw,[ref]$choice) -or $choice -lt 1 -or $choice -gt $mt5.Count){ throw 'MT5 选择无效。' }
}
$selected=$mt5[$choice-1]

$atasCandidates=@(
  (Join-Path $env:LOCALAPPDATA 'ATAS Platform'),
  (Join-Path $env:APPDATA 'ATAS Platform'),
  (Join-Path $env:ProgramFiles 'ATAS Platform'),
  (Join-Path ${env:ProgramFiles(x86)} 'ATAS Platform')
) | Where-Object {$_ -and (Test-Path $_)} | Select-Object -Unique
$atasPath=''
if($atasCandidates.Count -gt 0){
  Write-Host "`n检测到 ATAS 路径："
  for($i=0;$i -lt $atasCandidates.Count;$i++){Write-Host "[$($i+1)] $($atasCandidates[$i])"}
  $a=1
  if($atasCandidates.Count -gt 1){
    $raw=Read-Host '请输入 ATAS 编号'
    if(-not [int]::TryParse($raw,[ref]$a) -or $a -lt 1 -or $a -gt $atasCandidates.Count){throw 'ATAS 选择无效。'}
  }
  $atasPath=$atasCandidates[$a-1]
} else {
  Write-Warning '未自动检测到 ATAS。稍后可手工填写 Config/paths.yaml；这不会阻止 Guardian 本地保护。'
}

function YamlQuote([string]$v){ return '"' + (($v ?? '').Replace('\','/').Replace('"','\"')) + '"' }
$paths=@"
# Generated by Tools/install.ps1. Machine-specific paths only.
mt5:
  terminal_data_path: $(YamlQuote $selected.DataPath)
  terminal_origin: $(YamlQuote $selected.Origin)
  metaeditor_path: $(YamlQuote $selected.MetaEditor)
atas:
  install_path: $(YamlQuote $atasPath)
  bridge_target_path: ""
"@
Set-Content -Path (Join-Path $configDir 'paths.yaml') -Value $paths -Encoding UTF8
Write-Host '[Config] 已写入 Config/paths.yaml'

& (Join-Path $PSScriptRoot 'deploy_mt5.ps1') -TerminalDataPath $selected.DataPath -MetaEditorPath $selected.MetaEditor

if(-not $SkipPython){
  & (Join-Path $PSScriptRoot 'install_runtime.ps1')
}

$py=Join-Path $root 'Runtime\python\Scripts\python.exe'
if(Test-Path $py){
  & $py (Join-Path $PSScriptRoot 'validate_config.py')
  & $py (Join-Path $PSScriptRoot 'run_smoke_test.py')
}

Write-Host "`n=== 仓库侧自动安装步骤完成 ===" -ForegroundColor Green
Write-Host '仍需实机完成：ATAS SDK DataBridge 编译/加载、Rithmic Paper 连接、MT5 允许 127.0.0.1 Socket、模拟盘验收。'
